/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IletisimRouteImport } from './routes/iletisim'
import { Route as HakkindaRouteImport } from './routes/hakkinda'
import { Route as EserlerRouteImport } from './routes/eserler'
import { Route as IndexRouteImport } from './routes/index'

const IletisimRoute = IletisimRouteImport.update({
  id: '/iletisim',
  path: '/iletisim',
  getParentRoute: () => rootRouteImport,
} as any)
const HakkindaRoute = HakkindaRouteImport.update({
  id: '/hakkinda',
  path: '/hakkinda',
  getParentRoute: () => rootRouteImport,
} as any)
const EserlerRoute = EserlerRouteImport.update({
  id: '/eserler',
  path: '/eserler',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/eserler': typeof EserlerRoute
  '/hakkinda': typeof HakkindaRoute
  '/iletisim': typeof IletisimRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/eserler': typeof EserlerRoute
  '/hakkinda': typeof HakkindaRoute
  '/iletisim': typeof IletisimRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/eserler': typeof EserlerRoute
  '/hakkinda': typeof HakkindaRoute
  '/iletisim': typeof IletisimRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/eserler' | '/hakkinda' | '/iletisim'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/eserler' | '/hakkinda' | '/iletisim'
  id: '__root__' | '/' | '/eserler' | '/hakkinda' | '/iletisim'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EserlerRoute: typeof EserlerRoute
  HakkindaRoute: typeof HakkindaRoute
  IletisimRoute: typeof IletisimRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/iletisim': {
      id: '/iletisim'
      path: '/iletisim'
      fullPath: '/iletisim'
      preLoaderRoute: typeof IletisimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hakkinda': {
      id: '/hakkinda'
      path: '/hakkinda'
      fullPath: '/hakkinda'
      preLoaderRoute: typeof HakkindaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eserler': {
      id: '/eserler'
      path: '/eserler'
      fullPath: '/eserler'
      preLoaderRoute: typeof EserlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EserlerRoute: EserlerRoute,
  HakkindaRoute: HakkindaRoute,
  IletisimRoute: IletisimRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
